---
name: 📊 Feature Suggestion
about: Propose a new feature for the Apeiro addon suite
labels: enhancement
---

**Feature Name**

**Is your feature related to a problem?**
Explain what problem you're trying to solve.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Include mockups, logs, or examples if applicable.
