---
name: 📃 Spec Clarification
about: Ask for clarification or request elaboration on the official Apeiro specification
labels: documentation
---

**Spec Section**
(e.g., 2.3.1 ApeiroGridGroup)

**Clarification Needed**
Please explain what you're unsure about.

**What Have You Tried?**
Describe any interpretations you've considered.
